-- CreateTable
CREATE TABLE "Stores" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "owner" TEXT NOT NULL,
    "address" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "website" TEXT,
    "supportEmail" TEXT,
    "supportPhone" TEXT,
    "logoUrl" TEXT,
    "logoDarkUrl" TEXT,
    "timezone" TEXT,
    "currency" TEXT,
    "language" TEXT,
    "dateFormat" TEXT,
    "numberFormat" TEXT,
    "gstNumber" TEXT,
    "taxId" TEXT,
    "invoicePrefix" TEXT,
    "receiptFooter" TEXT,
    "defaultPaymentMethod" TEXT,
    "taxRate" DOUBLE PRECISION,
    "lowStockThreshold" INTEGER,
    "autoReorder" BOOLEAN DEFAULT false,
    "sessionTimeout" INTEGER DEFAULT 30,
    "enable2FA" BOOLEAN DEFAULT false,
    "roleBasedAccess" BOOLEAN DEFAULT true,
    "notificationEmail" TEXT,
    "sendLowStockEmail" BOOLEAN DEFAULT false,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Stores_pkey" PRIMARY KEY ("id")
);
